<%@ Page Language="C#" MasterPageFile="~/MasterPages/CICPage.master" AutoEventWireup="true"
    CodeFile="RoleMaster.aspx.cs" Inherits="Admin_Screens_RoleMaster" %>

<asp:Content ID="Content2" ContentPlaceHolderID="MainConHolder" runat="Server">
    <asp:UpdatePanel ID="pnlRoles" runat="server">
        <ContentTemplate>
            <table width="100%">
                <tr>
                    <td class="headingred">
                        Role Master
                    </td>
                    <td align="<%=ConfigurationManager.AppSettings["AjaxLoadingAlign"]%>" style="padding-right:10px;">
                        <asp:UpdateProgress ID="UpdateProgress2" runat="server">
                            <ProgressTemplate>
                                <img src="<%=ConfigurationManager.AppSettings["AjaxLoadingImageName"]%>" alt="" />
                            </ProgressTemplate>
                        </asp:UpdateProgress>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="bgcolorcomm" style="padding-left: 20px;">
                        <asp:GridView ID="gvRoles" RowStyle-CssClass="gridbgcolor" AlternatingRowStyle-CssClass="fieldName"
                            HeaderStyle-CssClass="fieldNamewithbgcolor" ShowHeader="true" runat="server"
                            CssClass="simpletxt1" AutoGenerateColumns="false" AutoGenerateDeleteButton="false"
                            GridLines="None" OnRowDeleting="gvRoles_RowDeleting"
                            OnRowDataBound="gvRoles_RowDataBound" Width="269px">
                            <Columns>
                            
                            <asp:CommandField ShowDeleteButton="True" HeaderStyle-Width="60px" HeaderText="">
                                <HeaderStyle Width="60px" />
                            </asp:CommandField>
                                <asp:TemplateField HeaderStyle-HorizontalAlign="Left" HeaderText="Role Name">
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="lblRoleName" Text='<%# Container.DataItem %>' />
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <b>Add Role</b>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="bgcolorcomm" style="padding-left: 20px;">
                       
                       <table width="100%"><tr><td>
                       
                        Enter Roll Name<font color='red'>*</font>
                        <asp:TextBox ID="txtRoleName" runat="server" CssClass="txtboxtxt"></asp:TextBox><asp:RequiredFieldValidator
                            ID="valReqRoleName" runat="server" ControlToValidate="txtRoleName" ErrorMessage="Role Name is required.">*</asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="padding-left: 20px;">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:Button ID="btnSubmit" runat="server" OnClick="btnSubmit_Click" text="Save" Width="70"
                            CssClass="btn" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                        <asp:Label ID="lblMessage" runat="server" ForeColor="Red" CssClass="simpletxt1"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td align="center" colspan="2">
                        <asp:Label ID="ActionStatus" ForeColor runat="server" CssClass="simpletxt1" Font-Bold="true"></asp:Label>
                  </td></tr></table>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        &nbsp;
                    </td>
                </tr>
            </table>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
